version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pytorch_deep_unet/requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv pytorch_deep_unet
            . pytorch_deep_unet/bin/activate
            pip install -r pytorch_deep_unet/requirements.txt

      - save_cache:
          paths:
            - ./pytorch_deep_unet
          key: v1-dependencies-{{ checksum "pytorch_deep_unet/requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . pytorch_deep_unet/bin/activate
            python -m unittest discover pytorch_deep_unet/

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
